drop table if exists Lotto;
create table lotto (
                       lotto_id bigint generated by default as identity,
                       fifthNum bigint not null,
                       firstNum bigint not null,
                       fourthNum bigint not null,
                       secondNum bigint not null,
                       sixthNum bigint not null,
                       thirdNum bigint not null,
                       uniqueCode varchar(255) not null,
                       store_id bigint,
                       primary key (lotto_id)
);